#!/usr/bin/bash
# This code write by (Ms.nope)
if [[ "$(id -u)" -ne 0 ]]; then
  echo "please run This programm as Root!"
  exit 1
fi
clear
echo "Updating..."
sleep 2
echo "

█▄▄ █▀█ █░█ ▀█▀ █▀▀ ▄▄ █▀▀ █▀█ █▀█ █▀▀ █▀▀
█▄█ █▀▄ █▄█ ░█░ ██▄ ░░ █▀░ █▄█ █▀▄ █▄▄ ██▄
"
cd .. && cd .. && rm -r Brute-Force && git clone https://github.com/msprogrammer2938/Brute-Force && cd Brute-Force
sleep 2
echo ""
echo "Finish Updating!"
echo ""
exit 
